### ISSUE TITLE
Compatibility with GEE models

### ISSUE THREAD

**Issue by MrJerryTAO** [strengejacke/ggeffects#327] opened 2023-05-15 04:29 UTC
In reading a tutorial at https://data.library.virginia.edu/getting-started-with-generalized-estimating-equations/ I noticed that "[2023-02-26 update] To create an effect plot for the GEE model fit by the gee package, we need to call emmeans() directly. When this article was originally published in April 2021, we could use ggeffects as we did above. However this is no longer the case due to changes in a dependent package. Thanks to Nathaniel Wilson for notifying us of this change."

**Comment by strengejacke** [comment] 2023-05-15 06:15
Do you have a reproducible example?

**Comment by strengejacke** [comment] 2023-05-15 10:19
Seems to be an issue of _insight_, closing in favor of https://github.com/easystats/insight/issues/770

**Closed by strengejacke** 2023-05-15 10:19 UTC
