### ISSUE TITLE
`rawdata=T` does not work for `plot(ggpredict())` applied to a logistic `glm()` with proportions as response variable

### ISSUE THREAD

**Issue by marcoplebani85** [strengejacke/ggeffects#370] opened 2023-08-31 08:03 UTC
Dear all,

The following dataset represents a hypothetical study on egg predation in bird nests found in areas with different vegetation cover. Vegetation cover (%) is the predictor, `brood.size` is the total number of eggs in each nest, `egg.predation` is how many eggs fell to predation, nests represent replicates:

```
rm(list=ls())
if (!require(pacman)) install.packages('pacman'); library(pacman)
p_load(ggplot2)
p_load(ggeffects)
p_load(RCurl)
# load data:
df <- read.csv(text = RCurl::getURL("https://raw.githubusercontent.com/marcoplebani85/datasets/master/egg_predation.csv"))
str(df)
```

I fitted a `glm()` model with the proportion of eggs subject to predation in each nest as the response variable, and `brood.size` as `weights`:

```
df$predation.proportion <- df$egg.predation/df$brood.size
glm.egg <- glm(predation.proportion ~ vegetation.cover,
	data = df,
	weights = brood.size,
	family = binomial(link="logit")
	)
glm.egg.ggpred <- ggpredict(glm.egg, terms=c("vegetation.cover [n=100]"))
```
All good so far. If I try to draw the `ggpredict()` predictions together with the raw data, a figure with the model predictions is produced, but the data are not shown and the message _**"Raw data not available."**_ is produced:
```
plot(glm.egg.ggpred, rawdata=T)
```
 I was able to add the data with `geom_point()`, but I don't understand why `rawdata=T` doesn't work in this case. I realise that `predation.proportion` data aren't technically "raw", but I don't see how that would be an issue. There are no NA in the column provided to `weights =`. I am using `ggeffects` version 1.3.0 from CRAN.

Is this a bug or am I missing something/doing something wrong? 

Many thanks in advance for your time and help.

Best

Marco

**Comment by strengejacke** [comment] 2023-09-04 10:34
seems to be same issue as in #372 

``` r
rm(list = ls())
if (!require(pacman)) install.packages("pacman")
#> Loading required package: pacman
library(pacman)
p_load(ggplot2)
p_load(ggeffects)
p_load(RCurl)
# load data:
df <- read.csv(text = RCurl::getURL("https://raw.githubusercontent.com/marcoplebani85/datasets/master/egg_predation.csv"))
str(df)
#> 'data.frame':    90 obs. of  3 variables:
#>  $ vegetation.cover: int  0 20 40 60 80 100 0 20 40 60 ...
#>  $ brood.size      : int  4 4 5 6 2 5 2 3 4 6 ...
#>  $ egg.predation   : int  4 2 0 0 0 0 2 1 0 0 ...

df$predation.proportion <- df$egg.predation / df$brood.size
glm.egg <- glm(predation.proportion ~ vegetation.cover,
  data = df,
  weights = brood.size,
  family = binomial(link = "logit")
)
glm.egg.ggpred <- ggpredict(glm.egg, terms = c("vegetation.cover [n=100]"))

plot(glm.egg.ggpred, add.data = TRUE)
#> Data points may overlap. Use the `jitter` argument to add some amount of
#>   random variation to the location of data points and avoid overplotting.
```

![](https://i.imgur.com/NhlREc9.png)

**Comment by marcoplebani85** [comment] 2023-09-04 14:19
Thanks! I updated the package with `ggeffects::install_latest()`. If I run the code in R version 4.3.1 (2023-06-16) it works correctly displaying both data and model predictions, **but** if I run the code in RStudio (the latest version: 2023.06.1+524) the problem persists. For completeness, I am working on a 2014 Apple Mac mini running MacOS Monterey version 12.6.1 (21G217)

**Comment by strengejacke** [comment] 2023-09-04 17:05
Closing as duplicate of #372

**Closed by strengejacke** 2023-09-04 17:05 UTC
