### ISSUE TITLE
weird plots with logistic glmer

### ISSUE THREAD

**Issue by mattansb** [strengejacke/ggeffects#227] opened 2021-07-08 07:51 UTC
``` r
d <- tibble::tribble(
  ~subId,  ~Condition, ~ProbeNum, ~ImageNum,        ~Answer,
  "118",  "Original",   "first",  "15.jpg", "Unrecognized",
  "103",  "Original",  "second",  "41.jpg",   "Recognized",
  "111",  "Original",   "first",  "32.jpg", "Unrecognized",
  "117", "Scrambled",   "first",  "26.jpg", "Unrecognized",
  "117",  "Original",  "second",  "31.jpg",   "Recognized",
  "101",  "Original",  "second",   "2.jpg",   "Recognized",
  "121",  "Original",  "second",   "1.jpg", "Unrecognized",
  "120", "Scrambled",   "first",  "12.jpg", "Unrecognized",
  "112", "Scrambled",  "second",  "28.jpg", "Unrecognized",
  "108",  "Original",   "first",  "29.jpg",   "Recognized"
)

d$Answer <- factor(d$Answer)

m <- lme4::glmer(Answer ~ Condition * ProbeNum + (1|subId) + (1|ImageNum),
                 family = binomial(),
                 data = d)
````

## Where is 200% from?
```R
ggeffects::ggemmeans(m, c("ProbeNum", "Condition")) |> plot(add.data = TRUE)
```

![](https://i.imgur.com/dTAP6Ae.png)

## Where are the dots?
``` r
ggeffects::ggemmeans(m, c("ProbeNum", "Condition")) |> plot(add.data = TRUE, collapse.group = "subId") 
```

![](https://i.imgur.com/jlLhAl7.png)

**Comment by strengejacke** [comment] 2022-02-06 11:01
Can't reproduce first example any longer. Is it also resolved for you?

``` r
d <- tibble::tribble(
  ~subId,  ~Condition, ~ProbeNum, ~ImageNum,        ~Answer,
  "118",  "Original",   "first",  "15.jpg", "Unrecognized",
  "103",  "Original",  "second",  "41.jpg",   "Recognized",
  "111",  "Original",   "first",  "32.jpg", "Unrecognized",
  "117", "Scrambled",   "first",  "26.jpg", "Unrecognized",
  "117",  "Original",  "second",  "31.jpg",   "Recognized",
  "101",  "Original",  "second",   "2.jpg",   "Recognized",
  "121",  "Original",  "second",   "1.jpg", "Unrecognized",
  "120", "Scrambled",   "first",  "12.jpg", "Unrecognized",
  "112", "Scrambled",  "second",  "28.jpg", "Unrecognized",
  "108",  "Original",   "first",  "29.jpg",   "Recognized"
)

d$Answer <- factor(d$Answer)

m <- lme4::glmer(Answer ~ Condition * ProbeNum + (1|subId) + (1|ImageNum),
                 family = binomial(),
                 data = d)
#> boundary (singular) fit: see ?isSingular

ggeffects::ggemmeans(m, c("ProbeNum", "Condition")) |> plot(add.data = TRUE)
#> Loading required namespace: emmeans
#> Loading required namespace: ggplot2
```

![](https://i.imgur.com/BkludiC.png)

<sup>Created on 2022-02-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment] 2022-02-06 11:06
For the second issue, this seems to be related to your `collapse_by_group()` function (I think this was implemented by you).

``` r
d <- tibble::tribble(
  ~subId,  ~Condition, ~ProbeNum, ~ImageNum,        ~Answer,
  "118",  "Original",   "first",  "15.jpg", "Unrecognized",
  "103",  "Original",  "second",  "41.jpg",   "Recognized",
  "111",  "Original",   "first",  "32.jpg", "Unrecognized",
  "117", "Scrambled",   "first",  "26.jpg", "Unrecognized",
  "117",  "Original",  "second",  "31.jpg",   "Recognized",
  "101",  "Original",  "second",   "2.jpg",   "Recognized",
  "121",  "Original",  "second",   "1.jpg", "Unrecognized",
  "120", "Scrambled",   "first",  "12.jpg", "Unrecognized",
  "112", "Scrambled",  "second",  "28.jpg", "Unrecognized",
  "108",  "Original",   "first",  "29.jpg",   "Recognized"
)

d$Answer <- factor(d$Answer)

m <- lme4::glmer(Answer ~ Condition * ProbeNum + (1|subId) + (1|ImageNum),
                 family = binomial(),
                 data = d)
#> boundary (singular) fit: see ?isSingular

pr <- ggeffects::ggemmeans(m, c("ProbeNum", "Condition"))
#> Loading required namespace: emmeans

ggeffects:::collapse_by_group(pr,
                              model = ggeffects:::.get_model_object(pr),
                              collapse.by = "subId",
                              residuals = FALSE)
#> Warning in mean.default(X[[i]], ...): argument is not numeric or logical:
#> returning NA

#> Warning in mean.default(X[[i]], ...): argument is not numeric or logical:
#> returning NA

#> Warning in mean.default(X[[i]], ...): argument is not numeric or logical:
#> returning NA

#> Warning in mean.default(X[[i]], ...): argument is not numeric or logical:
#> returning NA

#> Warning in mean.default(X[[i]], ...): argument is not numeric or logical:
#> returning NA

#> Warning in mean.default(X[[i]], ...): argument is not numeric or logical:
#> returning NA

#> Warning in mean.default(X[[i]], ...): argument is not numeric or logical:
#> returning NA

#> Warning in mean.default(X[[i]], ...): argument is not numeric or logical:
#> returning NA

#> Warning in mean.default(X[[i]], ...): argument is not numeric or logical:
#> returning NA

#> Warning in mean.default(X[[i]], ...): argument is not numeric or logical:
#> returning NA
#>    x group_col facet random response
#> 1  2  Original     1    101       NA
#> 2  2  Original     1    103       NA
#> 3  1  Original     1    108       NA
#> 4  1  Original     1    111       NA
#> 5  2 Scrambled     1    112       NA
#> 6  2  Original     1    117       NA
#> 7  1 Scrambled     1    117       NA
#> 8  1  Original     1    118       NA
#> 9  1 Scrambled     1    120       NA
#> 10 2  Original     1    121       NA
```

<sup>Created on 2022-02-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment] 2022-08-16 10:43
@mattansb _bump_

**Comment by mattansb** [comment] 2022-08-16 10:56
<sub>Writing my dissertation - see you in 2 months!</sub>

**Comment by strengejacke** [comment] 2023-04-28 06:15
I close this as fixed. Please re-open if there's still an issue.

**Closed by strengejacke** 2023-04-28 06:15 UTC
Labels: bug :bug:, waiting for response :love_letter:

**Comment by mattansb** [comment] 2023-04-28 07:56
Looks good - thanks!
