### ISSUE TITLE
"Controlling for" other variables doesn't work with rlmer models

### ISSUE THREAD

**Issue by UCDOakeslab** [strengejacke/ggeffects#155] opened 2020-08-24 23:52 UTC
Hello! First, thank you so much for making this package -- it's very good. 

I did run into an error with using `rlmer`. It looks as though you *must* include all of the DV's in the model with `ggpredict` statement to work otherwise it produces an error. In other words, you cannot get the "adjusted for..." function to work using the robust model. 

![Screen Shot 2020-08-24 at 4 50 22 PM](https://user-images.githubusercontent.com/36185165/91107342-eba92580-e629-11ea-862e-cc4c1c4f4b4a.png)

In the screenshot, `m_proplkTargSS4` refers to a model fit with lme4 and `m_proplkTargSS4_robust` refers to the model fit with `rlmer`. As you can see, an error is produced because I did not include the variable "age" in the `ggpredict` call.

**Comment by strengejacke** [comment] 2020-08-25 07:52
I'm not sure if it's really due to the missing age-variable. Do you have a reproducible example?

``` r
library(robustlmm)
library(lme4)
library(ggeffects)

data(sleepstudy)
sleepstudy$x <- rnorm(nrow(sleepstudy))

m <- rlmer(
  Reaction ~ Days + x + (Days | Subject),
  data = sleepstudy,
  rho.sigma.e = psi2propII(smoothPsi, k = 2.28),
  rho.sigma.b = chgDefaults(smoothPsi, k = 5.11, s = 10)
)

ggpredict(m, "Days")
#> 
#> # Predicted values of Reaction
#> # x = Days
#> 
#> x | Predicted |    SE |           95% CI
#> ----------------------------------------
#> 0 |    252.45 |  7.24 | [238.26, 266.64]
#> 1 |    263.18 |  7.22 | [249.03, 277.33]
#> 2 |    273.91 |  7.59 | [259.05, 288.78]
#> 3 |    284.65 |  8.29 | [268.41, 300.89]
#> 5 |    306.12 | 10.39 | [285.75, 326.48]
#> 6 |    316.85 | 11.67 | [293.97, 339.73]
#> 7 |    327.58 | 13.04 | [302.02, 353.15]
#> 9 |    349.05 | 15.97 | [317.74, 380.36]
#> 
#> Adjusted for:
#> *       x = 0.03
#> * Subject = 0 (population-level)
```

<sup>Created on 2020-08-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by UCDOakeslab** [comment] 2020-08-25 16:34
Hello! Thank you for your quick reply. Below is a reproducible example. I've learned that if the left-out variable is a factor variable, then the `ggpredict` function does not average over this factor (in this example, gender). I've used your example above (thank you!) and instead of adding variable "x", I added a factor variable "gender". 

I've also pasted an example of what I've done in the past using the `emmeans` function. As you can see, the `emmeans` package averages over the factor variable gender. Maybe this is something that has been done intentionally or maybe I am missing something about the way your package works. 


```
library(robustlmm)
library(lme4)
library(ggeffects)
library(emmeans)

data(sleepstudy)
sleepstudy$gender <- as.factor(rbinom(n = nrow(sleepstudy), prob = .5, size = 1))

m <- rlmer(
  Reaction ~ Days + gender + (Days | Subject),
  data = sleepstudy,
  rho.sigma.e = psi2propII(smoothPsi, k = 2.28),
  rho.sigma.b = chgDefaults(smoothPsi, k = 5.11, s = 10)
)

ggpredict(m, "Days") # doesn't work

# Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) : 
#   contrasts can be applied only to factors with 2 or more levels


# However, this appears to work (I think, though it doesn't say explicitly that this is averaged over "gender"):
ggeffect(m, "Days") 


## When fitting the model with lme4, the emmeans function averages over the factor variable "gender".
m_lme4 <- lmer(
  Reaction ~ Days + gender + (Days | Subject),
  data = sleepstudy)
emmeans(m_lme4, ~Days)

# Days emmean   SE df lower.CL upper.CL
# 4.5    298 9.05 17      279      318
# 
# Results are averaged over the levels of: gender 
# Degrees-of-freedom method: kenward-roger 
# Confidence level used: 0.95 
```

**Comment by strengejacke** [comment] 2020-08-26 06:46
Thanks, should be fixed now.

**Closed** 2020-08-26 06:46 UTC
Labels: reprex :floppy_disk:

**Comment by UCDOakeslab** [comment] 2020-08-27 01:18
Thank you very much!

-Michaela
