### ISSUE TITLE
error in ggemmeans(..type="fe.zi") with two-level factor

### ISSUE THREAD

**Issue by carushworth** [strengejacke/ggeffects#77] opened 2019-05-14 22:56 UTC
I'm getting an error when I use ggemmeans with type="fe.zi" (pretty similar to #53), but only with certain combinations of terms. The offending term is a factor with two levels (1 and 2; recoding as A and B, "CohAB", gives the same error). I may be missing something and using the function incorrectly. The relevant dataset is attached. 

The error is 
Error in exp(prdat.sim$cond) : non-numeric argument to mathematical function

```
library(glmmTMB) 
library(ggeffects)

data <- read.xlsx("example_data.xlsx",1)

fit <- glmmTMB(Seeds ~ Grp*Site + Coh + Grp:Coh + (1|Grp:Geno) + (1|Site:Block),
                   data=data,
                   ziformula=~Grp + Site,
                   family="nbinom2")

# works with or without zi
ggemmeans(fit,c("Grp","Site"),type="fe.zi")

# works without zi
ggemmeans(fit,c("Grp","Coh"))

# produces error
ggemmeans(fit,c("Grp","Coh"),type="fe.zi")
```
[example_data.xlsx](https://github.com/strengejacke/ggeffects/files/3180188/example_data.xlsx)

**Comment by rpmady** [comment] 2019-05-15 22:24
I'm also in a similar situation where I have a mixed model with nested random effects. My error is slightly different, but I figured it might be related? 

```
mod3 <- glmmTMB(sum.50 ~ location*trtmt + julian2 + min_aft_sunrise2 + mintemp2 + (1|site:day_mod), 
data = bcch_sub, 
ziformula=~1, 
family=nbinom1) 
```
When I try to run ``` ggpredict(mod3, terms = c("location","trtmt"), type="fe.zi")``` I get this error: 
```Error in eval(predvars, data, env) : object 'day_mod' not found```

**Comment by strengejacke** [comment] 2019-05-16 07:13
@carushworth The names in the data and the model differ, can you please fix this, so I'm running the same example?

**Comment by strengejacke** [comment] 2019-05-16 12:33
@rpmady Your issue should be fixed when you update https://github.com/easystats/insight from GitHub.

**Comment by carushworth** [comment] 2019-05-16 15:54
Apologies, I've edited the original comment and it should be correct now.

**Comment by strengejacke** [comment] 2019-05-16 19:06
Ok, this issue should be fixed, at least partially.

* The problem is that you have `Grp` involved in two interactions, but you're requesting marginal effects only for one interaction. That means for the second interaction (`Grp * Site`) that you ignore a higher order term, because you leave out `Site`. You can't use `type = "fe.zi"` unless you use `ggemmeans(fit, c("Grp", "Coh", "Site"), type = "fe.zi")`

* Second, and this was the issue I needed to fix, you use `Site` both as fixed effects and _grouping factor_ in the random effects (not as random slope, but as grouping factor). This is not expected by ggeffects, but fixed now, so you can do that. But I'm not sure if it makes sense to include a fixed effect also as _grouping factor_.

**Closed by strengejacke** 2019-05-16 19:06 UTC
Labels: awaiting response
