### ISSUE TITLE
Error with hurdle glmmTMB model (ggpredict)

### ISSUE THREAD

**Issue by VictorVdm** [strengejacke/ggeffects#147] opened 2020-07-22 15:29 UTC
Hello,

I have fitted a Hurdle model (with a truncated negative binomial for the count part), using the package glmmTMB.

``` r
model.count <- formula(nb_t ~
                         scale(a_r) + scale(a_n1_r) +
                         scale(a_s) + scale(a_n1_s) +
                         c +
                         c:scale(a_r) + c:scale(a_n1_r) + 
                         c:scale(a_s) + c:scale(a_n1_s) + 
                         c:scale(a_p) +
                         scale(a_p) +
                         pha+
                         scale(temp) + scale(prec) +
                         (1|ID_f))

model.zero <- formula(~ scale(a_r) + scale(a_n1_r) +
                        scale(a_s) + scale(a_n1_s) +
                        c +
                        c:scale(a_r) + c:scale(a_n1_r) + 
                        c:scale(a_s) + c:scale(a_n1_s) + 
                        c:scale(a_p) +
                        scale(a_p) +
                        pha+pro+
                        scale(temp) + scale(prec) +
                        nj+
                        (1|ID_f))


fit <- glmmTMB(model.count, ziformula = model.zero, 
                              family = truncated_nbinom2, data=dat)

ggpredict(fit, terms = c("a_n1_r"), type="fe") #working perfectly
ggpredict(fit, terms = c("a_n1_r"), type="zi.prob") #working perfectly

ggpredict(fieldcrops1000.fit, terms = c("a_n1_r"), type="fe.zi") #not working
```

I know my model is quite complex, but it seems ok without any convergence problems. 
ggpredict is working for conditional model only or zero model only (zero-inflation probability), but not with the two components (fe.zi). I get the following error : 

> Error in `$<-.data.frame`(`*tmp*`, "predicted", value = numeric(0)) : 
>   replacement has 0 rows, data has 250

Dataset is not public, but I attached  some modified data : [dat.zip](https://github.com/strengejacke/ggeffects/files/4960860/dat.zip).

Many thanks for your help !

**Comment by strengejacke** [comment] 2020-07-22 16:11
Thanks for reporting. Might be a duplicate of #53, can you please check?
If so, try standardizing your data before fitting the model, e.g., either using `sjmisc::std()` or `effectsize::standardize()`. Does it then work?

**Comment by strengejacke** [comment] 2020-07-22 16:25
Yes, seems to be a duplicate. Closing this in favor of #53. For the moment, I have added a more informative error message, telling the user what probably could have caused this issue and how to solve it.

**Closed** 2020-07-22 16:25 UTC
Labels: bug :bug:, duplicate :two_men_holding_hands:

**Comment by VictorVdm** [comment] 2020-07-22 18:12
Thank you for your responsiveness ! Sorry I did not look long enough.

**Comment by strengejacke** [comment] 2020-07-22 19:08
Don't worry, such issues are not obviously to "decipher"...
