### ISSUE TITLE
ggpredict can't find random effects term of model

### ISSUE THREAD

**Issue by KuepferA** [strengejacke/ggeffects#178] opened 2020-11-24 17:13 UTC
I get a similar issue to that originally posted by @rpmady (https://github.com/strengejacke/ggeffects/issues/77#issuecomment-492846225_), but don't understand the solution that was suggested ("Your issue should be fixed when you update https://github.com/easystats/insight from GitHub")

```
M7 <- glmmTMB(C ~ Vez  + Treatment + sDIM + sSS + sSample + RW + Season + (1|Unique_st/Unique_id), 
data=dfm7, 
offset = sLsum, 
family=nbinom2) 

```
When I try to run ``` > Mp7 <-ggpredict(M7, terms = c("Treatment"))``` 
I get this error: ```Error in eval(predvars, data, env) : object 'Unique_st' not found```

**Comment by strengejacke** [comment] 2020-11-24 17:31
Those issues shoudln't be related, because the other issue is probably too old. But still it might be that your issue is already resolved in the current developer (GitHub) version of ggeffects. Do you have a reproducible example? That would help me finding the bug.

**Comment by KuepferA** [comment] 2020-11-24 18:18
Thank you for your speedy response. I have posted a reproducible example.
Kind regards,

Amanda

Amanda Kuepfer
(MSc Marine Environmental Protection)

Doctoral Researcher (Seabird-Fisheries Interactions)

SAERI
FIFD
University of Exeter
ISPA
m: +500 65929
t: +500 27374

**Comment by strengejacke** [comment] 2020-11-24 19:56
I just realized that the offset-term cannot be found when it's included as argument. Usually, you would find the offset-term via the `call` element:

```r
mod <- glm(C ~ Vez  + Treatment + sDIM + sSS + sSample + RW + Season, data=dfm7, offset = sLsum, family = poisson)
mod$call$offset
#> sLsum
```

However, this does not work for glmmTMB. But you can workaround this by adding the offset to the formula:

```r
M7 <- glmmTMB(C ~ Vez  + Treatment + sDIM + sSS + sSample + RW + Season + offset(sLsum) + (1|Unique_st/Unique_id), data=dfm7, family=nbinom2)
```

``` r
library(glmmTMB)
library(ggeffects)
df1=read.csv("~/../Desktop/dfm7.csv", header = TRUE)

# create offset
df1$Lsum <- log(df1$sum)

#rescale continuous parameters
dfs<-df1
dfs$sDIM <- scale(dfs$DIM)[, 1]
dfs$sWS <- scale(dfs$WS)[, 1]
dfs$sSS <- scale(dfs$SS)[, 1]
dfs$sLsum <- scale(dfs$Lsum)[, 1]
dfs$sSample <- scale(dfs$New_Sample)[, 1]

# make dataframe unique to this model
dfm7 <- dfs
M7 <- glmmTMB(C ~ Vez  + Treatment + sDIM + sSS + sSample + RW + Season + offset(sLsum) + (1|Unique_st/Unique_id), data=dfm7, family=nbinom2)
Mp7 <-ggpredict(M7, terms = c("Treatment")) # this gives me error "Error in eval(predvars, data, env) : object 'Unique_st' not found"
Mp7
#> # Predicted counts of C
#> # x = Treatment
#> 
#> x | Predicted |        95% CI
#> -----------------------------
#> C |     13.57 | [6.94, 26.51]
#> B |     11.19 | [6.15, 20.36]
#> 
#> Adjusted for:
#> *       Vez =     A
#> *      sDIM =  0.00
#> *       sSS =  0.01
#> *   sSample = -0.04
#> *        RW =   dg4
#> *    Season =     C
#> *     sLsum = -0.01
#> * Unique_id = NA (population-level)
#> * Unique_st = NA (population-level)
```

<sup>Created on 2020-11-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by KuepferA** [comment] 2020-11-24 20:22
Brilliant,  That works perfectly!

Thank you very much for the very speedy assistance. I very much appreciate your time.

Kind regards


This email and any files transmitted with it are confidential and intended solely for the use of the individual(s) or entity named above.
If you have received this email in error you must not use, copy, distribute, disseminate or disclose the information contained in it.
Please notify us immediately, delete the email from your computer system, and destroy any hard copies you may have created.

**Closed** 2020-11-24 20:53 UTC

**Comment by strengejacke** [comment] 2020-11-24 20:55
I found a way how to solve your issue. With the next update of ggeffects, your example will work fine and no longer fail. You can also update ggeffects from GitHub, but you need to update insight from CRAN to the latest version as well.
