### ISSUE TITLE
Reference levels & odds ratios

### ISSUE THREAD

**Issue by jjcii** [strengejacke/ggeffects#66] opened 2019-03-15 01:11 UTC
I am currently examining marginal effects of some fixed effects factors in a mixed effects logistic.  To do so, I've employed `ggpredict`; I've then also used the `tab_model` function of the associated `sjPlot` package to produce tables that include odd ratios.  I'm incredibly impressed with both. However, I was a bit surprised by the output of each:

1) I now see that all levels of my factor predictors are included in the output (as opposed to R's usual dummy coding in which [one level of each factor serves as a reference][1] for contrasts).  Is it possible to retain a reference level in the `ggpredict` output?  I was hoping to use it to i) check against manual calculations and ii) compare it to the glmer model coefficients that are not similarly calculated conditionally upon the random effects.

2) The odds ratios provided by `tab_model` are identical to those that I obtained by exponentiating the coefficients provided by my original `glmer` model ([per the IDRE example procedure][2]).  However, I was under the impression that the ORs calculated were derived from marginal coefficients that did not account for the influence of the random effect in my model (see the paragraph starting with "Many people prefer" [here][3], the "Predicted Probabilities and Graphing" section [here][2], and top answer [here][4] for more information).  In turn, does this mean that the ORs for fixed effects variables provided by `tab_model` similarly do not account for the influence of the random effect?  If that's the case, is there an argument or other means by which to do so?

Thanks!

  [1]: https://stats.stackexchange.com/questions/60817/significance-of-categorical-predictor-in-logistic-regression
  [2]: https://stats.idre.ucla.edu/r/dae/mixed-effects-logistic-regression/
  [3]: https://stats.idre.ucla.edu/other/mult-pkg/introduction-to-generalized-linear-mixed-models/
  [4]: https://stats.stackexchange.com/questions/365907/interpretation-of-fixed-effects-from-mixed-effect-logistic-regression

**Comment by strengejacke** [comment] 2019-03-15 08:02
At 1) All levels are always included, it's just that the "reference" is represented by the intercept. Because you have an association (or effect) between your outcome and _each_ group of a factor. See this simple example, where we calculate the mean value of `mpg` for each category of `gear`. In the linear regression, the intercept has the same value as mean for category "3". The same is true for the predicted values from `ggpredict()`. If you calculate a model w/o intercept, all levels are shown in the output.

For the model with intercept, intercept (16.107) + coefficient of category "4" (8.427) is about ~24.5, i.e. the mean value of `mpg` for category 4 of `gear`.

``` r
library(ggeffects)
library(dplyr)

data(mtcars)
mtcars %>% 
  group_by(gear) %>% 
  summarise(mean_mpg = mean(mpg))
#> # A tibble: 3 x 2
#>    gear mean_mpg
#>   <dbl>    <dbl>
#> 1     3     16.1
#> 2     4     24.5
#> 3     5     21.4

m <- lm(mpg ~ as.factor(gear), data = mtcars)
summary(m)
#> 
#> Call:
#> lm(formula = mpg ~ as.factor(gear), data = mtcars)
#> 
#> Coefficients:
#>                  Estimate Std. Error t value Pr(>|t|)    
#> (Intercept)        16.107      1.216  13.250 7.87e-14 ***
#> as.factor(gear)4    8.427      1.823   4.621 7.26e-05 ***
#> as.factor(gear)5    5.273      2.431   2.169   0.0384 *  

ggpredict(m, "gear")
#> 
#> # Predicted values of mpg 
#> # x = gear 
#> 
#>  x predicted std.error conf.low conf.high
#>  3    16.107     1.216   13.724    18.489
#>  4    24.533     1.359   21.870    27.197
#>  5    21.380     2.106   17.253    25.507

m <- lm(mpg ~ 0 + as.factor(gear), data = mtcars)
summary(m)
#> 
#> Coefficients:
#>                  Estimate Std. Error t value Pr(>|t|)    
#> as.factor(gear)3   16.107      1.216   13.25 7.87e-14 ***
#> as.factor(gear)4   24.533      1.359   18.05  < 2e-16 ***
#> as.factor(gear)5   21.380      2.106   10.15 4.66e-11 ***
```

At 2) The OR always condition on the fixed effects only. Since you have variation in your groups (represented by the random effects), this OR would differ at each group-level, which in turn will result in many different OR-values for the same predictor. This is not common to report. Instead, you typicall present an additional table with the variation in the random effects (e.f. `ranef(model)` or `sjPlot::plot_model(model, type = "re")`). To get predicted probabilities (or more general, marginal effects) at different group-levels for random effects, see [this vignette](https://strengejacke.github.io/ggeffects/articles/randomeffects.html).

I'm closing this, since it seems to me not being an "issue" in terms of bug-report, but feel free to reply or ask for further clarification in this thread.

**Closed by strengejacke** 2019-03-15 08:02 UTC

**Comment by jjcii** [comment] 2019-03-15 16:00
Thanks, Daniel.  Apologies for posting questions that indeed relate more to my own familiarity with what the packages are doing rather than bug-related issues.  More, I appreciate the example walk-through and results presentation; I'm new to marginal effects with mixed models so this is quite helpful.  To that end, taking you up on the invitation to request further clarification (much appreciated), I had a some follow-up items.

At 1) I follow and am acquainted with the relationship between intercepts and reference levels with linear regressions.  However, in the case of my [here-simplified to a single factor] logistic regression without the intercept....


`> m1 <- glm(Choice ~ 0 + as.factor(MAMType), data = d_AllProfiles, family = binomial)`
`> summary(m1)`

`Coefficients:`
`                              Estimate Std. Error z value Pr(>|z|)    `
`as.factor(MAMType)Inactive    -2.70142    0.06640  -40.68   <2e-16 ***`
`as.factor(MAMType)Coactive    -3.08326    0.06942  -44.41   <2e-16 ***`
`as.factor(MAMType)RiskAvoider -3.17383    0.07651  -41.48   <2e-16 ***`
`as.factor(MAMType)RiskTaker   -3.26910    0.06885  -47.48   <2e-16 ***`

... coefficients are not identical to the values provided by ggpredict:

`> ggpredict(m1, terms = "MAMType")`

`# Predicted probabilities of Choice `
`# x = MAMType `

 `x predicted std.error conf.low conf.high`
 `1     0.063     0.066    0.056     0.071`
 `2     0.044     0.069    0.038     0.050`
 `3     0.040     0.077    0.035     0.046`
 `4     0.037     0.069    0.032     0.042`

I presume everything is functioning correctly (noting the corresponding standard errors for each variable in the two outputs), however, can you comment on the relationship between the values for predicted marginal effects vs. model coefficients in the case of logistics?

At 2) Regarding results presentation, the odds ratios in your paper reflect fixed effects with random effect of country then presented separately, correct?  In other words, the odds ratios reflect the fixed effects were country to be held constant?

3) A broader conceptual clarification:  the `marginal_coefs` function of the [GLMMAdaptive package ](https://drizopoulos.github.io/GLMMadaptive/articles/Methods_MixMod.html)provides marginal coefficients when working with mixed models.  Are you familiar enough to comment on whether these values represent the same information provided by the the `ggpredict` output in the case of fixed effects in mixed models?  I was hoping to iterate to colleagues any conceptual distinction.

Thanks so much.

**Comment by strengejacke** [comment] 2019-03-15 22:00
At 1) For linear models, you have an "identity"-link, i.e. coefficients and response are on the same scale. For non-Gaussian models, you have a [link-function](https://en.wikipedia.org/wiki/Generalized_linear_model#Link_function), that's why the coefficients are on a different scale than your response. The response, `Choice` in your example, either has a "success" or "failure" (i.e. it is 0/1 or whatever binary coding it has). So you can express that "Choice" happens as a probability, the ratio between "success" and "failure". So, the response scale in logit-models is on a probability scale, and `ggpredict()` always returns predictions on the response scale (because this is what in most cases is required, to interprete marginal effects, or marginal "means"). That's why predicted values for binomial-models are "predicted probabilities". Due to the link-function, you can't directly compare predicted values with the raw coefficients. Furthermore, dropping the intercept is probably less appropriate in logistic regression models.

At 2)
> Regarding results presentation, the odds ratios in your paper reflect fixed effects with random effect of country then presented separately, correct? 

Yes. 

> In other words, the odds ratios reflect the fixed effects were country to be held constant?

Not directly. The variation of the random effects lead to ["shrinkage"](https://www.tjmahr.com/plotting-partial-pooling-in-mixed-effects-models/) of the fixed effects, a useful property, since it's "corrects" extreme variation in "outlier groups". So the fixed effects, or coefficients, represent the relationship between response and predictor for an average "group" (or subject, or whatever you have as random effect), and "adjusted" for extreme cases (i.e. extreme high or low coefficients are "pulled" to the grand mean of the outcome).

> In my case, I'm looking at the fixed effect of MAMType (respondents belong to one of four) while trying to account for the random intercepts of individuals that provided repeated observations.

With a mixed model (in your case, random-slope-intercept), you can the "correct" fixed effects, because your model takes autocorrelation (repeated observation) and group-variation into account. That's why you get different estimates (fixed effects) from a mixed model compared to a simple model. You can, however, also make [prediction for different levels of random effects](https://strengejacke.github.io/ggeffects/articles/randomeffects.html).

At 3) Marginalized coefficients are not marginal effects (predicted values). Marginal coefficients are fixed effects / estimates that represent the relationship between response and predictor, _averaging over all random effects_ (so they refer to the "population" average effect, instead of a "group" average or "group specific" effect of an average group - you may replace "group" with "subject" here). However, these are only different for non-Gaussian models. For linear models, "normal" coefficients and marginal coefficients should be the same.

Regarding our paper in PlosOne: the Odds Ratio of any coefficient (i.e. the relatoinship between predictor and outcome) is different in each country, and the Odds Ratios in the table represent an average effect of a country (not of the total sample, i.e. the "whole population").

But again: marginal _effects_ (as produced by `ggpredict()` are not the same as marginal coefficients. However, by default, predicted values are on the "population level", i.e. they average over all random effects by default, unless you specify the random effect levels (see again: https://strengejacke.github.io/ggeffects/articles/randomeffects.html).

**Comment by jjcii** [comment] 2019-03-16 22:47
Thanks so much, Daniel - this is **incredibly** helpful, on all fronts.  

If I may, I've one final question regarding presentation, with your paper's odds ratios serving as example. You noted the ratios represent _"an average effect of a country (not the total sample, i.e., 'whole population')"_; would if thus be appropriate to report "For the **average country**, a change in status was approximately 19% more likely when carers were female (model 1)", or does convention not require that prefacing so long as the random effects stats are also presented?  (Alternatively, could a population-level OR be exponentiated from the FE marginal coefficients offered by `GLMMAdaptive` rather than the FE coefficients provided by `glmer`?)

**Comment by strengejacke** [comment] 2019-03-24 22:10
> "For the average country, a change in status was approximately 19% more likely when carers were female (model 1)",

I think my description was a bit unclear. The odds ratios, when effects are not marginal coefficients, can be interpreted like this: the odds ratio of _a_ country. It does not refer to a specific country, but this is the effect for _any_ country, _within_ this country. Marginal coefficients would mean: average effect for all or over all countries, so here we have the odds of an _average_ country.

**Comment by jjcii** [comment] 2019-03-29 17:03
Understood.  Thanks again, Daniel!

**Comment by jukicivan** [comment] 2021-02-27 02:35
I apologise in advance for jumping here on @jjcii's thread, but I have a very similar question, and would appreciate if you ( @strengejacke and maybe even @jjcii) could help me out. I must mention that this is my first time dealing with marginal effects, odds-ratios (OR-s), and mixed-modelling. Please disregard and delete this post if you find it inappropriate. 

I did a lot of searching and reading, mainly on CV and SE, and I also read your Plos ONE paper, but I still have some doubts regarding marginal effects, OR-s and their interpretation. Briefly, in my study, I was looking at the proportion of instances (YES, NO or 1, 0) in which people managed to stay above pre-determined fatigue threshold during three different experimental conditions while performing the same task in each conditions 3 times. Importantly, all participants went through all the procedures. In that regard, I ran mixed effects logistic regression using `glmer` from `lme4` package. 

```
 glmer(frequency ~ condition*task_number + (1 + condition + task_number|name), 
 family = binomial,
 contrasts = list(condition = "contr.sum", task_number = "contr.sum"),
 data = data, 
 control =  glmerControl(optimizer = "bobyqa"))
```

This is the final model I came up with, and this model passed all the checks using `DHARMa` package and everything was fine. Next, I was interested in the pairwise comparisons between the conditions to determine which condition was more effective in maintaining fatigue levels above the pre-determined threshold, and for that purpose I used `emmeans` package.

```
a <- emmeans(model, "condition", by = "task_number",  type = "response")
contrast(a, method = "pairwise", adjust = "holm")
```

This gave me OR-s for all the comparisons between conditions by the task number (because they all performed the same task 3 times during each condition) and all the relevant statistics. However, I also used `ggpredict` and got predicted probabilities which I then plotted using my own `ggplot` code. I'm now in doubt how to interpret all of this because I was getting confused about the ability to generalise when using `glmer`similar to @jjcii's concerns in the second question of this thread. I'm also now unsure whether it is redundant to report both comparisons and predicted probabilities. The way I see it now is that:

a) OR-s comparisons give me the information about which condition for a given task number is more effective at keeping the fatigue levels above a pre-determined threshold (e.g., during the first task, condition 1 had ~68% less chance to stay above fatigue threshold when compared to condition condition 2 [OR = 0.323, SE = 0.126, Z = 2.888,  p =0.0055]); 
 
b) Predicted probabilities give me the information of the overall probability for staying above the pre-determined fatigue threshold during each condition and the task number. 

I'm now unsure, like I said, whether it is redundant to report both, and also am I correctly interpreting my OR-s (I'm mainly concerned here if they should be "bounded" to my particular case, because I don't know if they are taking into account my random factors). Also, I'm unsure if I'm interpreting predicted probabilities here, and, what is the conceptual difference between OR's and predicted probabilities? It seems to me that, in my case, first one is "inferential" whereas the other is more "descriptive". 

I apologise again for jumping in here, and thank you very much if you consider replying to it.
